#!/bin/sh

# user is already defined
hostname="$(uname -n)"
os='Artix Linux'
kernel="$(uname -r | sed 's/-.*//')"
uptime="$(uptime -p | sed 's/ days,/d/g;s/ day,/d/g;s/up //g;s/ hours,/h/g;s/ hour/h/g;s/ minutes/m/g;s/ minute/m/g')"
packages="$(pacman -Q | wc -l)"
wm="$(awk '/exec/ {print $2}' $XINITRC)"

## DEFINE COLORS

# probably don't change these
if [ -x "$(command -v tput)" ]; then
	bold="$(tput bold)"
	black="$(tput setaf 0)"
	red="$(tput setaf 1)"
	green="$(tput setaf 2)"
	yellow="$(tput setaf 3)"
	blue="$(tput setaf 4)"
	magenta="$(tput setaf 5)"
	cyan="$(tput setaf 6)"
	white="$(tput setaf 7)"
	reset="$(tput sgr0)"
fi

# you can change these
lc="${reset}${bold}${blue}"         # labels
nc="${reset}${bold}${blue}"         # user and hostname
ic="${reset}"                       # info
c0="${reset}${blue}"                # first color

## OUTPUT

cat <<EOF

${c0}        /\         ${nc}${USER}${ic}@${nc}${hostname}${reset}
${c0}       /  \        ${white}-------------------${reset}
${c0}      /\`'.,\       ${lc}os      ${ic}${os}${reset}
${c0}     /     '\      ${lc}kernel  ${ic}${kernel}${reset}
${c0}    /      ,\`\     ${lc}uptime  ${ic}${uptime}${reset}      
${c0}   /   ,.'\`.  \    ${lc}pkgs    ${ic}${packages}${reset}   
${c0}  /.,'\`     \`'.\   ${lc}wm      ${ic}${wm}${reset}

EOF
